---
version: 2.1
jobs:

  build_spm:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - spm_cache
    - run: mkdir -p ~/docker
    - run:
        command: |
          if [[ -e ~/docker/spm.tar ]]; then
            docker load -i ~/docker/spm.tar;
          fi
          docker build -t bids/spm:latest -f ./spm/Dockerfile .
          docker save "bids/spm:latest" > ~/docker/spm.tar
    - save_cache:
        key: spm_cache
        paths:
        - ~/docker

  build_ants:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - ants_cache
    - run: mkdir -p ~/docker
    - run:
        name: build ants
        command: |
          if [[ -e ~/docker/ants.tar ]]; then
            docker load -i ~/docker/ants.tar;
          fi
          docker build -t bids/ants:latest -f ./ants/Dockerfile .
          docker save "bids/ants:latest" > ~/docker/ants.tar
    - save_cache:
        key: ants_cache
        paths:
        - ~/docker

  build_freesurfer:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - freesurfer_cache
    - run: mkdir -p ~/docker
    - run:
        name: build freesurfer
        command: |
          if [[ -e ~/docker/freesurfer.tar ]]; then
            docker load -i ~/docker/freesurfer.tar;
          fi
          docker build -t bids/freesurfer:latest -f ./freesurfer/Dockerfile .
          docker save "bids/freesurfer:latest" > ~/docker/freesurfer.tar
    - save_cache:
        key: freesurfer_cache
        paths:
        - ~/docker

  build_afni:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - afni_cache
    - run: mkdir -p ~/docker
    - run:
        name: build afni
        command: |
          if [[ -e ~/docker/afni.tar ]]; then
            docker load -i ~/docker/afni.tar;
          fi
          docker build -t bids/afni:latest -f ./afni/Dockerfile .
          docker save "bids/afni:latest" > ~/docker/afni.tar
    - save_cache:
        key: afni_cache
        paths:
        - ~/docker

workflows:
  build_deploy:
    jobs:
    - build_spm
    - build_ants
    - build_freesurfer
    - build_afni


# VS Code Extension Version: 1.5.1
