---
version: 2.1
jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2

    parameters:
      software:
        type: string

    steps:
      - checkout

      - restore_cache:
          keys:
            - << parameters.software >>_cache

      - run: mkdir -p ~/docker

      - run:
          name: building << parameters.software >>
          command: |
            if [[ -e ~/docker/<< parameters.software >>.tar ]]; then
              docker load -i ~/docker/<< parameters.software >>.tar;
            fi
            docker build -t bids/base_<< parameters.software >>:latest -f ./<< parameters.software >>/Dockerfile .
            docker save "bids/base_<< parameters.software >>:latest" > ~/docker/<< parameters.software >>.tar

      - run:
          name: push << parameters.software >> to dockerhub
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin
              echo "Pushing to DockerHub bids/base_<< parameters.software >>:unstable"
              docker tag bids/base_<< parameters.software >> bids/base_<< parameters.software >>:unstable
              docker push bids/base_<< parameters.software >>:unstable
              if [[ -n "${CIRCLE_TAG}" ]]; then
                echo "Pushing to DockerHub bids/base_<< parameters.software >>:${CIRCLE_TAG}"
                docker push bids/base_<< parameters.software >>:latest
                docker tag bids/base_<< parameters.software >> bids/base_<< parameters.software >>:${CIRCLE_TAG}
                docker push bids/base_<< parameters.software >>:${CIRCLE_TAG};
              fi
            else
              echo "No DOCKER_PASS, skipping push to DockerHub"
            fi

      - save_cache:
          key: spm_cache
          paths:
            - ~/docker

workflows:
  build_deploy:
    jobs:
      - build:
          matrix:
            parameters:
              software: ["spm", "afni", "freesurfer", "ants", "spm_octave"]
